const {createClient}=supabase;
const db=createClient(SHI_CONFIG.SUPABASE_URL,SHI_CONFIG.SUPABASE_KEY);
let user=null,cart=JSON.parse(localStorage.getItem("shi_cart")||"[]"),authMode="login",admin=false,addresses=[];

const $=id=>document.getElementById(id);
const money=n=>"฿"+Number(n||0).toLocaleString("th-TH",{minimumFractionDigits:2,maximumFractionDigits:2});
function toast(s){$("toast").textContent=s;$("toast").style.display="block";setTimeout(()=>$("toast").style.display="none",2800)}
function openModal(id){if(!user&&["topupModal","withdrawModal","addressModal","checkoutModal"].includes(id)){openModal("authModal");return}$(id).classList.add("open")}
function closeModal(id){$(id).classList.remove("open")}
function toggleCart(){$("cart").classList.toggle("open")}
function saveCart(){localStorage.setItem("shi_cart",JSON.stringify(cart));renderCart()}
function escapeHtml(s){return String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}

document.querySelectorAll("[data-view]").forEach(b=>b.onclick=()=>showView(b.dataset.view));
function showView(v){document.querySelectorAll(".view").forEach(x=>x.classList.remove("active"));$(v).classList.add("active");if(v==="wallet")loadWallet();if(v==="orders")loadOrders();if(v==="account")loadAccount();if(v==="admin"&&admin)loadAdmin("topups")}

$("authBtn").onclick=()=>user?logout():openModal("authModal");
$("switchAuth").onclick=()=>{authMode=authMode==="login"?"signup":"login";$("authTitle").textContent=authMode==="login"?"เข้าสู่ระบบ":"สมัครสมาชิก";$("authSubmit").textContent=authMode==="login"?"เข้าสู่ระบบ":"สมัครสมาชิก";$("authName").classList.toggle("hidden",authMode==="login");$("switchAuth").textContent=authMode==="login"?"ยังไม่มีบัญชี? สมัครสมาชิก":"มีบัญชีแล้ว? เข้าสู่ระบบ"};
$("authForm").onsubmit=async e=>{e.preventDefault();let email=$("authEmail").value.trim(),password=$("authPassword").value;
let r=authMode==="login"?await db.auth.signInWithPassword({email,password}):await db.auth.signUp({email,password,options:{data:{full_name:$("authName").value.trim()}}});
if(r.error)return toast(r.error.message);closeModal("authModal");if(authMode==="signup"&&!r.data.session)toast("สมัครสำเร็จ กรุณายืนยันอีเมลก่อนเข้าสู่ระบบ");else toast("เข้าสู่ระบบสำเร็จ");await refreshAuth()};

async function refreshAuth(){let r=await db.auth.getUser();user=r.data.user;admin=false;if(user){let a=await db.from("admin_roles").select("user_id").eq("user_id",user.id).maybeSingle();admin=!!a.data}$("adminBtn").classList.toggle("hidden",!admin);$("userLabel").textContent=user?(user.email||user.id):"ยังไม่ได้เข้าสู่ระบบ";$("authBtn").textContent=user?"ออกจากระบบ":"เข้าสู่ระบบ";if(user){await loadProfile();await loadCategories();await loadProducts();}else{await loadCategories();await loadProducts()}}
async function logout(){await db.auth.signOut();cart=[];saveCart();await refreshAuth();showView("shop")}
db.auth.onAuthStateChange(()=>setTimeout(refreshAuth,0));

async function loadCategories(){let r=await db.from("categories").select("*").eq("active",true).order("sort_order");$("category").innerHTML='<option value="">ทุกหมวดหมู่</option>'+(r.data||[]).map(c=>`<option value="${c.id}">${escapeHtml(c.name)}</option>`).join("")}
async function loadProducts(){let q=db.from("products").select("*,categories(name)").eq("active",true).order("created_at",{ascending:false});let cat=$("category").value,search=$("search").value.trim();if(cat)q=q.eq("category_id",cat);if(search)q=q.ilike("name","%"+search+"%");let r=await q;$("products").innerHTML=(r.data||[]).map(p=>`<article class="product"><img src="${p.image_url||'data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 width=%22600%22 height=%22600%22><rect width=%22100%%22 height=%22100%%22 fill=%22%2320242d%22/><text x=%2250%%22 y=%2250%%22 fill=%22white%22 text-anchor=%22middle%22 dominant-baseline=%22middle%22 font-size=%2240%22>SHI STORE</text></svg>'}"><div class="product-body"><h3>${escapeHtml(p.name)}</h3><div class="muted">${escapeHtml(p.categories?.name||"")}</div><div class="price">${money(p.price)}</div><div class="muted">คงเหลือ ${p.stock}</div><button class="primary full" ${p.stock<1?"disabled":""} onclick='addCart(${JSON.stringify({id:p.id,name:p.name,price:p.price})})'>เพิ่มลงตะกร้า</button></div></article>`).join("")||'<div class="card">ยังไม่มีสินค้า</div>'}
$("search").oninput=loadProducts;$("category").onchange=loadProducts;

function addCart(p){let x=cart.find(i=>i.id===p.id);if(x)x.qty++;else cart.push({...p,qty:1});saveCart();toggleCart()}
function renderCart(){let total=0;$("cartItems").innerHTML=cart.map(i=>{total+=i.price*i.qty;return `<div class="cart-item"><span>${escapeHtml(i.name)} × ${i.qty}</span><span>${money(i.price*i.qty)} <button onclick="removeCart('${i.id}')">×</button></span></div>`}).join("")||'<div class="muted">ตะกร้าว่าง</div>';$("cartTotal").textContent=money(total)}
function removeCart(id){cart=cart.filter(i=>i.id!==id);saveCart()}

async function checkout(){if(!user){openModal("authModal");return}if(!cart.length)return toast("ตะกร้าว่าง");await loadAddresses();if(!addresses.length){showView("account");openModal("addressModal");return}let total=cart.reduce((s,i)=>s+i.price*i.qty,0);$("checkoutSummary").innerHTML=`<p>สินค้า ${cart.length} รายการ</p><h3>${money(total)}</h3>`;$("addressSelect").innerHTML=addresses.map(a=>`<option value="${a.id}">${escapeHtml(a.recipient_name)} — ${escapeHtml(a.address_line)}</option>`).join("");openModal("checkoutModal")}
async function placeOrder(){let id=$("addressSelect").value;if(!id)return;let items=cart.map(i=>({product_id:i.id,quantity:i.qty}));let r=await db.rpc("create_order",{p_items:items,p_address_id:id});if(r.error)return toast(r.error.message);cart=[];saveCart();closeModal("checkoutModal");toast("สั่งซื้อสำเร็จ");showView("orders");loadOrders()}

async function loadWallet(){if(!user){$("balance").textContent="กรุณาเข้าสู่ระบบ";return}let w=await db.from("wallets").select("balance").eq("user_id",user.id).maybeSingle();$("balance").textContent=money(w.data?.balance);let t=await db.from("wallet_transactions").select("*").eq("user_id",user.id).order("created_at",{ascending:false}).limit(50);$("transactions").innerHTML=(t.data||[]).map(x=>`<div class="admin-row"><b>${escapeHtml(x.note||x.type)}</b><br><span class="muted">${new Date(x.created_at).toLocaleString("th-TH")}</span><span style="float:right">${money(x.amount)} · คงเหลือ ${money(x.balance_after)}</span></div>`).join("")||'<div class="muted">ยังไม่มีรายการ</div>'}
async function loadPaymentAccounts(){let r=await db.from("payment_accounts").select("*").eq("active",true).order("sort_order");let arr=r.data||[];$("paymentSelect").innerHTML=arr.map(a=>`<option value="${a.id}">${escapeHtml(a.provider_name)} — ${escapeHtml(a.account_name)} — ${escapeHtml(a.account_number)}</option>`).join("");$("paymentAccounts").innerHTML=arr.map(a=>`<div class="payment"><b>${escapeHtml(a.provider_name)}</b><br>${escapeHtml(a.account_name)}<br>${escapeHtml(a.account_number)}<br><span class="muted">${escapeHtml(a.instructions||"โอนเงินสำหรับซื้อสินค้า")}</span>${a.qr_image_path?`<img src="${db.storage.from("payment-qr").getPublicUrl(a.qr_image_path).data.publicUrl}">`:""}</div>`).join("")}
$("topupModal").addEventListener("transitionend",loadPaymentAccounts); // harmless
document.querySelector('[onclick="openModal(\'topupModal\')"]')?.addEventListener("click",loadPaymentAccounts);
$("topupForm").onsubmit=async e=>{e.preventDefault();if(!user)return;let file=$("slip").files[0];if(!file)return toast("กรุณาแนบสลิป");let path=`${user.id}/${crypto.randomUUID()}-${file.name.replace(/[^a-zA-Z0-9._-]/g,"_")}`;let up=await db.storage.from("payment-slips").upload(path,file,{contentType:file.type,upsert:false});if(up.error)return toast(up.error.message);let r=await db.rpc("request_topup",{p_payment_account_id:$("paymentSelect").value,p_amount:Number($("topupAmount").value),p_slip_path:path});if(r.error){await db.storage.from("payment-slips").remove([path]);return toast(r.error.message)}closeModal("topupModal");e.target.reset();toast("ส่งรายการเติมเงินแล้ว รอแอดมินตรวจสอบ");loadWallet()}

$("withdrawForm").onsubmit=async e=>{e.preventDefault();let r=await db.rpc("request_withdrawal",{p_amount:Number($("wdAmount").value),p_provider:$("wdProvider").value.trim(),p_account_name:$("wdName").value.trim(),p_account_number:$("wdNumber").value.trim()});if(r.error)return toast(r.error.message);closeModal("withdrawModal");e.target.reset();toast("ส่งคำขอถอนเงินแล้ว");loadWallet()}

async function loadProfile(){let r=await db.from("profiles").select("*").eq("id",user.id).maybeSingle();$("fullName").value=r.data?.full_name||"";$("phone").value=r.data?.phone||""}
$("profileForm").onsubmit=async e=>{e.preventDefault();let r=await db.from("profiles").update({full_name:$("fullName").value.trim(),phone:$("phone").value.trim(),updated_at:new Date().toISOString()}).eq("id",user.id);toast(r.error?r.error.message:"บันทึกแล้ว")}
async function loadAddresses(){let r=await db.from("addresses").select("*").eq("user_id",user.id).order("is_default",{ascending:false}).order("created_at",{ascending:false});addresses=r.data||[];$("addresses").innerHTML=addresses.map(a=>`<div class="admin-row"><b>${escapeHtml(a.recipient_name)}</b> ${a.is_default?'<span class="status">หลัก</span>':""}<br>${escapeHtml(a.phone)}<br>${escapeHtml(a.address_line)} ${escapeHtml(a.subdistrict)} ${escapeHtml(a.district)} ${escapeHtml(a.province)} ${escapeHtml(a.postal_code)}<br><button onclick="deleteAddress('${a.id}')">ลบ</button></div>`).join("")||'<div class="muted">ยังไม่มีที่อยู่</div>'}
async function loadAccount(){if(!user){$("addresses").innerHTML="กรุณาเข้าสู่ระบบ";return}await loadAddresses()}
$("addressForm").onsubmit=async e=>{e.preventDefault();if($("addrDefault").checked){await db.from("addresses").update({is_default:false}).eq("user_id",user.id)}let r=await db.from("addresses").insert({user_id:user.id,recipient_name:$("addrName").value.trim(),phone:$("addrPhone").value.trim(),address_line:$("addrLine").value.trim(),subdistrict:$("addrSub").value.trim(),district:$("addrDist").value.trim(),province:$("addrProv").value.trim(),postal_code:$("addrZip").value.trim(),is_default:$("addrDefault").checked});if(r.error)return toast(r.error.message);closeModal("addressModal");e.target.reset();toast("บันทึกที่อยู่แล้ว");loadAddresses()}
async function deleteAddress(id){let r=await db.from("addresses").delete().eq("id",id);toast(r.error?r.error.message:"ลบแล้ว");loadAddresses()}

async function loadOrders(){if(!user){$("ordersList").innerHTML="กรุณาเข้าสู่ระบบ";return}let r=await db.from("orders").select("*,order_items(*)").eq("user_id",user.id).order("created_at",{ascending:false});$("ordersList").innerHTML=(r.data||[]).map(o=>`<div class="admin-row"><b>#${o.id.slice(0,8)}</b> <span class="status">${escapeHtml(o.status)}</span><span style="float:right">${money(o.total_amount)}</span><br><span class="muted">${new Date(o.created_at).toLocaleString("th-TH")} · ${escapeHtml(o.shipping_recipient)} · ${escapeHtml(o.shipping_phone)}</span><br>${(o.order_items||[]).map(i=>`${escapeHtml(i.product_name)} × ${i.quantity}`).join(" · ")}${o.tracking_number?`<br>เลขพัสดุ: ${escapeHtml(o.tracking_number)}`:""}</div>`).join("")||'<div class="muted">ยังไม่มีคำสั่งซื้อ</div>'}

let adminTab="topups";
document.querySelectorAll("[data-admin]").forEach(b=>b.onclick=()=>{adminTab=b.dataset.admin;document.querySelectorAll("[data-admin]").forEach(x=>x.classList.remove("active"));b.classList.add("active");loadAdmin(adminTab)});
async function loadAdmin(tab){if(!admin)return;adminTab=tab;let box=$("adminContent");if(tab==="topups"){let r=await db.from("topups").select("*").order("created_at",{ascending:false}).limit(100);box.innerHTML="<h2>รายการเติมเงิน</h2>"+(r.data||[]).map(t=>`<div class="admin-row"><b>${money(t.amount)}</b> <span class="status">${t.status}</span><br>ผู้ใช้ ${t.user_id.slice(0,8)} · ${new Date(t.created_at).toLocaleString("th-TH")}<br><button onclick="reviewTopup('${t.id}','approve')" ${t.status!=="pending"?"disabled":""}>อนุมัติ</button> <button onclick="reviewTopup('${t.id}','reject')" ${t.status!=="pending"?"disabled":""}>ปฏิเสธ</button> <button onclick="viewSlip('${t.slip_path}')">ดูสลิป</button></div>`).join("")}
else if(tab==="withdrawals"){let r=await db.from("withdrawals").select("*").order("created_at",{ascending:false}).limit(100);box.innerHTML="<h2>รายการถอนเงิน</h2>"+(r.data||[]).map(w=>`<div class="admin-row"><b>${money(w.amount)}</b> <span class="status">${w.status}</span><br>${escapeHtml(w.provider_name)} · ${escapeHtml(w.account_name)} · ${escapeHtml(w.account_number)}<br><button onclick="reviewWithdrawal('${w.id}','approve')" ${w.status!=="pending"?"disabled":""}>อนุมัติ</button> <button onclick="reviewWithdrawal('${w.id}','reject')" ${w.status!=="pending"?"disabled":""}>ปฏิเสธ/คืนเงิน</button></div>`).join("")}
else if(tab==="products"){let r=await db.from("products").select("*").order("created_at",{ascending:false});box.innerHTML=`<h2>จัดการสินค้า</h2><form id="productForm" class="admin-grid"><input name="name" placeholder="ชื่อสินค้า" required><input name="slug" placeholder="slug" required><input name="price" type="number" step=".01" placeholder="ราคา" required><input name="stock" type="number" placeholder="สต็อก" required><input name="image_url" placeholder="URL รูปภาพ"><select name="category_id"><option value="">ไม่ระบุหมวด</option></select><textarea name="description" placeholder="รายละเอียด"></textarea><label><input name="active" type="checkbox" checked> เปิดขาย</label><button class="primary">เพิ่มสินค้า</button></form><hr>`+(r.data||[]).map(p=>`<div class="admin-row"><b>${escapeHtml(p.name)}</b> · ${money(p.price)} · stock ${p.stock} · ${p.active?"เปิด":"ปิด"}<br><button onclick="toggleProduct('${p.id}',${!p.active})">${p.active?"ปิดขาย":"เปิดขาย"}</button> <button onclick="deleteProduct('${p.id}')">ลบ</button></div>`).join("");let c=await db.from("categories").select("*").eq("active",true).order("sort_order");$("productForm").querySelector('[name="category_id"]').innerHTML='<option value="">ไม่ระบุหมวด</option>'+(c.data||[]).map(x=>`<option value="${x.id}">${escapeHtml(x.name)}</option>`).join("");$("productForm").onsubmit=async e=>{e.preventDefault();let f=new FormData(e.target),r=await db.from("products").insert({name:f.get("name"),slug:f.get("slug"),price:Number(f.get("price")),stock:Number(f.get("stock")),image_url:f.get("image_url")||null,description:f.get("description")||null,category_id:f.get("category_id")||null,active:f.get("active")==="on"});toast(r.error?r.error.message:"เพิ่มสินค้าแล้ว");loadAdmin("products");loadProducts()}
}
else if(tab==="payments"){let r=await db.from("payment_accounts").select("*").order("sort_order");box.innerHTML=`<h2>บัญชีรับเงิน</h2><form id="payForm" class="admin-grid"><input name="provider_name" placeholder="ธนาคาร/ผู้ให้บริการ" required><input name="account_name" placeholder="ชื่อบัญชี" required><input name="account_number" placeholder="เลขบัญชี" required><input name="sort_order" type="number" value="0"><input name="instructions" value="โอนเงินสำหรับซื้อสินค้า" placeholder="ข้อความ"><input name="qr" type="file" accept="image/*"><label><input name="active" type="checkbox" checked> เปิดรับเงิน</label><button class="primary">เพิ่มบัญชี</button></form><hr>`+(r.data||[]).map(p=>`<div class="admin-row"><b>${escapeHtml(p.provider_name)}</b> · ${escapeHtml(p.account_name)} · ${escapeHtml(p.account_number)} · ${p.active?"เปิด":"ปิด"}<br><button onclick="togglePayment('${p.id}',${!p.active})">${p.active?"ปิด":"เปิด"}</button> <button onclick="deletePayment('${p.id}')">ลบ</button></div>`).join("");$("payForm").onsubmit=async e=>{e.preventDefault();let f=new FormData(e.target),path=null,file=f.get("qr");if(file&&file.size){path=`${crypto.randomUUID()}-${file.name.replace(/[^a-zA-Z0-9._-]/g,"_")}`;let u=await db.storage.from("payment-qr").upload(path,file,{upsert:false});if(u.error)return toast(u.error.message)}let r=await db.from("payment_accounts").insert({provider_name:f.get("provider_name"),account_name:f.get("account_name"),account_number:f.get("account_number"),qr_image_path:path,instructions:f.get("instructions")||"โอนเงินสำหรับซื้อสินค้า",sort_order:Number(f.get("sort_order")||0),active:f.get("active")==="on"});toast(r.error?r.error.message:"เพิ่มบัญชีแล้ว");loadAdmin("payments");loadPaymentAccounts()}
}
else if(tab==="orders"){let r=await db.from("orders").select("*").order("created_at",{ascending:false}).limit(100);box.innerHTML="<h2>คำสั่งซื้อทั้งหมด</h2>"+(r.data||[]).map(o=>`<div class="admin-row"><b>#${o.id.slice(0,8)}</b> ${money(o.total_amount)} <span class="status">${o.status}</span><br>${escapeHtml(o.shipping_recipient)} · ${escapeHtml(o.shipping_phone)}<br><button onclick="setOrderStatus('${o.id}','processing')">กำลังเตรียม</button> <button onclick="setOrderStatus('${o.id}','shipped')">จัดส่งแล้ว</button> <button onclick="setOrderStatus('${o.id}','completed')">สำเร็จ</button><input id="trk-${o.id}" placeholder="เลขพัสดุ"><button onclick="setTracking('${o.id}')">บันทึกเลขพัสดุ</button></div>`).join("")}
else if(tab==="banners"){let r=await db.from("banners").select("*").order("sort_order");box.innerHTML=`<h2>แบนเนอร์</h2><form id="bannerForm" class="admin-grid"><input name="title" placeholder="หัวข้อ"><input name="subtitle" placeholder="คำโปรย"><input name="image_url" placeholder="URL รูป"><input name="link_url" placeholder="ลิงก์"><input name="sort_order" type="number" value="0"><label><input name="active" type="checkbox" checked> แสดง</label><button class="primary">เพิ่มแบนเนอร์</button></form><hr>`+(r.data||[]).map(b=>`<div class="admin-row"><b>${escapeHtml(b.title||"ไม่มีหัวข้อ")}</b> · ${b.active?"แสดง":"ซ่อน"}<br><button onclick="toggleBanner('${b.id}',${!b.active})">${b.active?"ซ่อน":"แสดง"}</button> <button onclick="deleteBanner('${b.id}')">ลบ</button></div>`).join("");$("bannerForm").onsubmit=async e=>{e.preventDefault();let f=new FormData(e.target),r=await db.from("banners").insert({title:f.get("title")||null,subtitle:f.get("subtitle")||null,image_url:f.get("image_url")||null,link_url:f.get("link_url")||null,sort_order:Number(f.get("sort_order")||0),active:f.get("active")==="on"});toast(r.error?r.error.message:"เพิ่มแล้ว");loadAdmin("banners");loadBanners()}
}}
async function reviewTopup(id,action){let s=await db.auth.getSession(),r=await fetch(`${SHI_CONFIG.SUPABASE_URL}/functions/v1/${SHI_CONFIG.TOPUP_FUNCTION}`,{method:"POST",headers:{Authorization:`Bearer ${s.data.session.access_token}`, "Content-Type":"application/json"},body:JSON.stringify({topup_id:id,action})});let j=await r.json().catch(()=>({}));toast(r.ok?"ดำเนินการแล้ว":j.error||"เกิดข้อผิดพลาด");loadAdmin("topups")}
async function reviewWithdrawal(id,action){let s=await db.auth.getSession(),reason=action==="reject"?prompt("เหตุผลที่ปฏิเสธ (เว้นว่างได้)"):"";if(action==="reject"&&reason===null)return;let r=await fetch(`${SHI_CONFIG.SUPABASE_URL}/functions/v1/${SHI_CONFIG.WITHDRAW_FUNCTION}`,{method:"POST",headers:{Authorization:`Bearer ${s.data.session.access_token}`,"Content-Type":"application/json"},body:JSON.stringify({withdrawal_id:id,action,reason})});let j=await r.json().catch(()=>({}));toast(r.ok?"ดำเนินการแล้ว":j.error||"เกิดข้อผิดพลาด");loadAdmin("withdrawals")}
async function viewSlip(path){let r=await db.storage.from("payment-slips").createSignedUrl(path,600);if(r.data?.signedUrl)window.open(r.data.signedUrl,"_blank");else toast(r.error?.message||"เปิดสลิปไม่ได้")}
async function toggleProduct(id,a){await db.from("products").update({active:a,updated_at:new Date().toISOString()}).eq("id",id);loadAdmin("products");loadProducts()}
async function deleteProduct(id){if(confirm("ลบสินค้า?")){await db.from("products").delete().eq("id",id);loadAdmin("products");loadProducts()}}
async function togglePayment(id,a){await db.from("payment_accounts").update({active:a,updated_at:new Date().toISOString()}).eq("id",id);loadAdmin("payments");loadPaymentAccounts()}
async function deletePayment(id){if(confirm("ลบบัญชีรับเงิน?")){await db.from("payment_accounts").delete().eq("id",id);loadAdmin("payments");loadPaymentAccounts()}}
async function toggleBanner(id,a){await db.from("banners").update({active:a}).eq("id",id);loadAdmin("banners");loadBanners()}
async function deleteBanner(id){if(confirm("ลบแบนเนอร์?")){await db.from("banners").delete().eq("id",id);loadAdmin("banners");loadBanners()}}
async function setOrderStatus(id,status){let r=await db.from("orders").update({status,updated_at:new Date().toISOString()}).eq("id",id);toast(r.error?r.error.message:"อัปเดตแล้ว");loadAdmin("orders");loadOrders()}
async function setTracking(id){let v=$("trk-"+id).value.trim();if(!v)return;let r=await db.from("orders").update({tracking_number:v,updated_at:new Date().toISOString()}).eq("id",id);toast(r.error?r.error.message:"บันทึกแล้ว");loadAdmin("orders")}
async function loadBanners(){let r=await db.from("banners").select("*").eq("active",true).order("sort_order");$("banners").innerHTML=(r.data||[]).map(b=>`<div class="banner" ${b.image_url?`style="background-image:linear-gradient(#0008,#0008),url('${b.image_url}') ;background-size:cover;background-position:center"`:""}><h2>${escapeHtml(b.title||"SHI STORE")}</h2><div>${escapeHtml(b.subtitle||"ร้านค้าออนไลน์")}</div></div>`).join("")}
$("musicBtn").onclick=()=>{let a=$("bgm");if(a.paused){a.play().then(()=>{$("musicBtn").textContent="♫ ON"}).catch(()=>toast("เบราว์เซอร์ไม่อนุญาตให้เล่นอัตโนมัติ กรุณากดอีกครั้ง"))}else{a.pause();$("musicBtn").textContent="♫"}};
loadBanners();renderCart();refreshAuth();
